# Generated by Django 6.1.1 on 2026-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilprestataire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
