# Generated by Django 6.1.1 on 2026-09-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_every_demand_has_a_provider(apps, schema_editor):
    """Block the nullable-to-required change until legacy data is resolved."""

    DemandePrestation = apps.get_model("prestations", "DemandePrestation")
    if DemandePrestation.objects.filter(prestataire__isnull=True).exists():
        raise RuntimeError(
            "Migration interrompue : chaque DemandePrestation doit avoir "
            "un ProfilPrestataire avant de rendre prestataire obligatoire."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_every_demand_has_a_provider,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='demandeprestation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeprestation',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_recues', to='profiles.profilprestataire'),
        ),
    ]
