# Generated by Django 6.1.1 on 2026-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0003_demandeprestation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeprestation',
            name='date_realisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeprestation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeprestation',
            name='validation_automatique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandeprestation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('REALISEE', 'Réalisée, en attente de validation'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
