# Generated by Django 6.1.1 on 2026-10-07 16:24

import apps.prestations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0004_demandeprestation_date_realisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointeDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PHOTO', 'Photo')], default='PHOTO', max_length=20)),
                ('fichier', models.FileField(upload_to=apps.prestations.models.chemin_piece_jointe)),
                ('mime', models.CharField(max_length=100)),
                ('taille', models.PositiveIntegerField()),
                ('nom_original', models.CharField(blank=True, max_length=120)),
                ('analyse_ia', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='prestations.demandeprestation')),
                ('deposee_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes_demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
    ]
