# Generated by Django 6.1.1 on 2026-09-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_repair_missing_username_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
