# Generated by Django 6.1.1 on 2026-10-02 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def marquer_comptes_existants_verifies(apps, schema_editor):
    """Comptes créés AVANT la vérification par e-mail : considérés vérifiés.

    Sans cela, tous les comptes existants seraient bloqués d'un coup sur
    les actions qui exigent un e-mail confirmé. email_verified_at reste
    vide : on distingue ainsi ces comptes de ceux qui ont réellement
    cliqué sur un lien de confirmation.
    """

    User = apps.get_model("accounts", "User")
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Les nouveaux comptes restent à False (valeur par défaut du champ).
        migrations.RunPython(marquer_comptes_existants_verifies, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
