# Generated by Django 6.1.1 on 2026-09-14 13:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestataireService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unite', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('competences', models.ManyToManyField(blank=True, related_name='offres_prestataires', to='services.competence')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_proposes', to='profiles.profilprestataire')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_prestataires', to='services.service')),
            ],
            options={
                'ordering': ['service__nom', 'prix'],
            },
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
        migrations.AddConstraint(
            model_name='prestataireservice',
            constraint=models.UniqueConstraint(fields=('prestataire', 'service'), name='unique_prestataire_service'),
        ),
    ]
