# Generated by Django 6.1.1 on 2026-09-14 13:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_prestataireservice_delete_tarif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataireservice',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
