# Generated by Django 6.1.1 on 2026-09-20 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestations', '0003_demandeprestation_service'),
        ('profiles', '0001_initial'),
        ('services', '0003_alter_prestataireservice_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='profiles.profilprestataire')),
            ],
            options={
                'ordering': ['jour_semaine', 'heure_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='disponibilite_heure_fin_apres_heure_debut')],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_pris', to=settings.AUTH_USER_MODEL)),
                ('demande_prestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='prestations.demandeprestation')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous_recus', to='profiles.profilprestataire')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='services.service')),
            ],
            options={
                'ordering': ['-date_heure_debut'],
                'indexes': [models.Index(fields=['prestataire', 'date_heure_debut'], name='rendezvous__prestat_3be7a4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_heure_fin__gt', models.F('date_heure_debut'))), name='rendezvous_heure_fin_apres_heure_debut')],
            },
        ),
    ]
