# Generated by Django 6.1.1 on 2026-09-20 16:11

import apps.verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_profilprestataire_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIdentite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to=apps.verification.models.chemin_document)),
                ('statut', models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ANALYSE', 'En analyse'), ('A_VERIFIER', 'À vérifier'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ANALYSE', max_length=20)),
                ('donnees_extraites', models.JSONField(blank=True, null=True)),
                ('resultat_comparaison', models.JSONField(blank=True, null=True)),
                ('score_correspondance', models.FloatField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('prestataire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_identite', to='profiles.profilprestataire')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verifies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
