# Generated by Django 6.1.1 on 2026-09-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilprestataire_date_naissance'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentidentite',
            name='type_document',
            field=models.CharField(choices=[('PIECE_IDENTITE', "Pièce d'identité"), ('DIPLOME', 'Diplôme'), ('CERTIFICATION', 'Certification'), ('DOCUMENT_PROFESSIONNEL', 'Document professionnel')], default='PIECE_IDENTITE', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentidentite',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_identite', to='profiles.profilprestataire'),
        ),
        migrations.AddConstraint(
            model_name='documentidentite',
            constraint=models.UniqueConstraint(fields=('prestataire', 'type_document'), name='unique_document_par_type_et_prestataire'),
        ),
    ]
