# Generated by Django 6.1.1 on 2026-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_documentidentite_type_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentidentite',
            name='date_analyse_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
