# Generated by Django 6.1.1 on 2026-10-02 12:25

import apps.verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def reprendre_prestataires_deja_verifies(apps, schema_editor):
    """Un prestataire déjà VERIFIE avant le parcours reçoit un dossier VALIDE :
    il n'est pas bloqué. decide_par reste vide, ce qui le distingue d'une
    décision prise dans le nouveau parcours."""

    ProfilPrestataire = apps.get_model("profiles", "ProfilPrestataire")
    DossierVerification = apps.get_model("verification", "DossierVerification")
    EvenementDossier = apps.get_model("verification", "EvenementDossier")
    for profil in ProfilPrestataire.objects.filter(statut_verification="VERIFIE"):
        dossier = DossierVerification.objects.create(
            prestataire=profil,
            statut="VALIDE",
            decision="VALIDE",
            motif_decision="Profil vérifié avant la mise en place du parcours de vérification.",
        )
        EvenementDossier.objects.create(
            dossier=dossier, type="REPRISE", message="Dossier repris : profil déjà vérifié auparavant."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilprestataire_date_naissance'),
        ('services', '0003_alter_prestataireservice_prix'),
        ('verification', '0003_documentidentite_date_analyse_debut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('PROFIL_A_COMPLETER', 'Profil à compléter'), ('DOCUMENTS_A_FOURNIR', 'Documents à fournir'), ('DOCUMENTS_EN_ANALYSE', 'Documents en analyse'), ('COHERENCE_A_VERIFIER', 'Cohérence à vérifier'), ('ENTRETIEN_A_FAIRE', 'Entretien à faire'), ('ENTRETIEN_TERMINE', 'Entretien terminé'), ('DOSSIER_EN_REVUE', 'Dossier en revue'), ('VALIDE', 'Validé'), ('A_VERIFIER', 'À vérifier (renvoyé au prestataire)'), ('REJETE', 'Rejeté')], default='PROFIL_A_COMPLETER', max_length=30)),
                ('metier', models.CharField(blank=True, max_length=120)),
                ('zone_intervention', models.CharField(blank=True, max_length=255)),
                ('disponibilites_declarees', models.CharField(blank=True, max_length=255)),
                ('conversation_profil', models.JSONField(blank=True, default=list)),
                ('profil_termine_le', models.DateTimeField(blank=True, null=True)),
                ('analyse_competence', models.JSONField(blank=True, null=True)),
                ('analyse_coherence', models.JSONField(blank=True, null=True)),
                ('coherence_calculee_le', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('VALIDE', 'Validé'), ('A_VERIFIER', 'À vérifier'), ('REJETE', 'Rejeté')], max_length=20)),
                ('motif_decision', models.TextField(blank=True)),
                ('etape_a_reprendre', models.CharField(blank=True, choices=[('profil', 'Profil'), ('identite', 'Identité'), ('competences', 'Compétences'), ('entretien', 'Entretien')], max_length=20)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.categorie')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_decides', to=settings.AUTH_USER_MODEL)),
                ('prestataire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_verification', to='profiles.profilprestataire')),
                ('services_declares', models.ManyToManyField(blank=True, related_name='+', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='EntretienVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('INTERROMPU', 'Interrompu')], default='EN_COURS', max_length=20)),
                ('consentement_le', models.DateTimeField()),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duree_secondes', models.PositiveIntegerField(blank=True, null=True)),
                ('mode', models.CharField(default='regles', max_length=10)),
                ('questions', models.JSONField(default=list)),
                ('echanges', models.JSONField(default=list)),
                ('question_courante', models.PositiveSmallIntegerField(default=1)),
                ('relances_question_courante', models.PositiveSmallIntegerField(default=0)),
                ('transcription', models.TextField(blank=True)),
                ('enregistrement', models.FileField(blank=True, upload_to=apps.verification.models.chemin_enregistrement)),
                ('enregistrement_type', models.CharField(blank=True, max_length=50)),
                ('rapport', models.JSONField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='verification.dossierverification')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='EvenementDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='verification.dossierverification')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.RunPython(reprendre_prestataires_deja_verifies, migrations.RunPython.noop),
    ]
