# Generated by Django 6.1.1 on 2026-10-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_parcours_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierverification',
            name='analyse_identite',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierverification',
            name='synthese',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossierverification',
            name='synthese_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
