# Generated by Django 6.1.1 on 2026-10-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_analyse_identite_synthese'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementdossier',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
