# Generated by Django 6.1.1 on 2026-09-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
        ('prestations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedevis',
            name='demande_prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_devis', to='prestations.demandeprestation'),
        ),
    ]
