# Generated by Django 6.1.1 on 2026-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_devis_direct_fields_and_reponse_details'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reponsedevis',
            constraint=models.UniqueConstraint(fields=('demande', 'prestataire'), name='unique_reponse_prestataire_demande'),
        ),
    ]
