# Generated by Django 6.1.1 on 2026-09-27 19:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_reponsedevis_unique_reponse_prestataire_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsedevis',
            name='conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reponsedevis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reponsedevis',
            name='date_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reponsedevis',
            name='description_frais',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reponsedevis',
            name='montant_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reponsedevis',
            name='montant_main_oeuvre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='LigneMateriau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unite', models.CharField(blank=True, max_length=30)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_materiaux', to='devis.reponsedevis')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
