# Generated by Django 6.1.1 on 2026-10-08 07:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestations', '0005_piecejointedemande'),
        ('profiles', '0002_profilprestataire_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPreparee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEMANDE', 'Demande de prestation'), ('RENDEZ_VOUS', 'Rendez-vous'), ('DEVIS', 'Demande de devis'), ('MESSAGE', 'Message'), ('DIAGNOSTIC', 'Diagnostic')], max_length=16)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PRETE_A_CONFIRMER', 'Prête à confirmer'), ('CONFIRMEE', 'Confirmée'), ('EXECUTEE', 'Exécutée'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée'), ('ECHEC', 'Échec')], default='BROUILLON', max_length=24)),
                ('donnees_preparees', models.JSONField(blank=True, default=dict)),
                ('resultat_backend', models.JSONField(blank=True, default=dict)),
                ('confirmation_expresse_le', models.DateTimeField(blank=True, null=True)),
                ('executee_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='FicheBesoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description_client', models.TextField(blank=True)),
                ('urgence_declaree', models.CharField(blank=True, max_length=40)),
                ('localisation_declaree', models.JSONField(blank=True, default=dict)),
                ('budget_min_client', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max_client', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observations_medias', models.JSONField(blank=True, default=list)),
                ('informations_backend', models.JSONField(blank=True, default=dict)),
                ('decisions_client', models.JSONField(blank=True, default=dict)),
                ('diagnostic_accepte', models.BooleanField(blank=True, null=True)),
                ('recommandations_mimo', models.JSONField(blank=True, default=dict)),
                ('diagnostic_requis', models.BooleanField(blank=True, null=True)),
                ('justification_diagnostic', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('prestataire_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_mimo_choisies', to='profiles.profilprestataire')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_media', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio')], max_length=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ANALYSE', 'Analyse en cours'), ('TERMINEE', 'Terminée'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=16)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('limites', models.JSONField(blank=True, default=list)),
                ('metadata_analyse', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_analyse', models.DateTimeField(blank=True, null=True)),
                ('fiche_besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_medias', to='mimo.fichebesoin')),
                ('piece_jointe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_mimo', to='prestations.piecejointedemande')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MimoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EN_ATTENTE_CLIENT', 'En attente du client'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=24)),
                ('etat_courant', models.CharField(default='COMPREHENSION', max_length=80)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_mimo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='JournalMimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evenement', models.CharField(choices=[('MESSAGE_CLIENT', 'Message client'), ('MESSAGE_MIMO', 'Message MIMO'), ('OUTIL_APPELE', 'Outil appelé'), ('OUTIL_REPONDU', 'Outil répondu'), ('RECOMMANDATION', 'Recommandation'), ('DECISION_CLIENT', 'Décision client'), ('ACTION_PREPAREE', 'Action préparée'), ('CONFIRMATION', 'Confirmation'), ('ACTION_EXECUTEE', 'Action exécutée'), ('ACTION_REFUSEE', 'Action refusée')], max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('action_preparee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='mimo.actionpreparee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='mimo.mimosession')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.AddField(
            model_name='fichebesoin',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_besoin', to='mimo.mimosession'),
        ),
        migrations.AddField(
            model_name='actionpreparee',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_preparees', to='mimo.mimosession'),
        ),
        migrations.AddConstraint(
            model_name='fichebesoin',
            constraint=models.CheckConstraint(condition=models.Q(('budget_min_client__isnull', True), ('budget_max_client__isnull', True), ('budget_max_client__gte', models.F('budget_min_client')), _connector='OR'), name='mimo_budget_client_coherent'),
        ),
    ]
