# Generated by Django 6.1.1 on 2026-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaanalyse',
            name='fichier',
            field=models.FileField(blank=True, upload_to='mimo/medias/'),
        ),
    ]
