"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# ------------------------------------------------------------------
# En français simple :
# Ce fichier contient TOUS les réglages du backend MIMOSY :
# base de données, sécurité, applications installées, JWT,
# temps réel, paiement PayDunya, IA, etc.
#
# La plupart des valeurs sont lues dans les "variables d'environnement"
# (fichier .env ou .env.docker). Ainsi, on ne met jamais de mot de passe
# ou de clé secrète directement dans le code.
# ------------------------------------------------------------------
from datetime import timedelta
from decimal import Decimal
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import os

# Charge le fichier .env (s'il existe) dans les variables d'environnement.
load_dotenv()

# BASE_DIR = le dossier back_Mimosy/. On s'en sert pour construire les
# chemins (media, fichiers statiques...).
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(nom_variable, valeur_defaut):
    """Convertit une variable d'environnement en booléen sans piège.

    os.getenv() renvoie toujours une chaîne : bool("False") vaut True
    en Python, donc un simple bool(os.getenv(...)) rendrait DEBUG=False
    inopérant. On compare explicitement la chaîne obtenue à un ensemble
    de valeurs reconnues comme vraies.
    """

    valeur = os.getenv(nom_variable)

    if valeur is None:
        return valeur_defaut

    return valeur.strip().lower() in ("1", "true", "yes", "on")


def env_list(nom_variable, valeur_defaut=""):
    """Découpe une variable d'environnement en liste, sur les virgules.

    Utilisé pour ALLOWED_HOSTS, CORS_ALLOWED_ORIGINS et
    CSRF_TRUSTED_ORIGINS : les espaces autour de chaque valeur sont
    retirés et les entrées vides sont ignorées.
    """

    valeur = os.getenv(nom_variable, valeur_defaut)

    return [item.strip() for item in valeur.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True : mode développement (messages d'erreur détaillés).
# En production, il faut absolument DEBUG=False.
DEBUG = env_bool("DEBUG", True)

# La clé secrète sert à signer les données sensibles (sessions, jetons...).
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if DEBUG:
        # Clé de secours pour le développement local uniquement. Elle
        # est volontairement générique et ne protège rien de réel :
        # elle sert seulement à ce qu'un nouveau développeur puisse
        # lancer le projet sans avoir configuré de fichier .env au
        # préalable. Elle ne doit jamais être utilisée en production.
        SECRET_KEY = "django-insecure-dev-only-set-DJANGO_SECRET_KEY-in-env"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY doit être défini dans les variables "
            "d'environnement lorsque DEBUG=False."
        )

# Liste des noms de domaine autorisés à appeler ce serveur.
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

# Liste des applications chargées par Django. Chaque dossier de apps/
# correspond à une partie du métier (comptes, devis, paiement...).
INSTALLED_APPS = [
    # Daphne doit être avant django.contrib.staticfiles : il remplace alors la
    # commande « runserver » par un serveur ASGI, capable de gérer HTTP et
    # WebSocket. Les requêtes HTTP sont traitées exactement comme avant.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    # Django Channels : couche temps réel (WebSocket), voir config/asgi.py.
    'channels',

    # MIMOSY
    'apps.accounts',
    'apps.locations',
    'apps.profiles',
    'apps.services',
    'apps.prestations',
    'apps.devis',
    'apps.rendezvous',
    'apps.verification',
    'apps.wallet',
    'apps.messaging',
    'apps.notifications',
    'apps.reviews',
    'apps.reports',
    'apps.disputes',
    'apps.trust',
    'apps.diagnosis',
    'apps.adminpanel',
    # Couche temps réel : tickets et connexions WebSocket (voir docs/temps-reel.md).
    'apps.realtime',
    "drf_spectacular",

    # Liste noire des refresh tokens JWT, utilisée pour invalider un
    # token au moment de la déconnexion (voir apps.accounts.views.LogoutView).
    "rest_framework_simplejwt.token_blacklist",
]
# Réglages de Django REST Framework (DRF), la librairie qui fabrique l'API :
#  - authentification par jeton JWT ;
#  - par défaut, il faut être connecté pour appeler l'API ;
#  - limitation du nombre de requêtes (anti-abus).
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    # Limites de base appliquées à toutes les requêtes, plus des scopes
    # dédiés pour les endpoints les plus exposés aux abus (login,
    # inscription, envoi de message). Ces valeurs conviennent au
    # développement et à un usage normal ; elles devront être ajustées
    # une fois le trafic réel de production connu.
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_RATE_ANON", "100/min"),
        "user": os.getenv("THROTTLE_RATE_USER", "300/min"),
        "login": os.getenv("THROTTLE_RATE_LOGIN", "10/min"),
        "register": os.getenv("THROTTLE_RATE_REGISTER", "10/min"),
        "message": os.getenv("THROTTLE_RATE_MESSAGE", "30/min"),
        # Délivrance des tickets de connexion WebSocket (POST /api/ws/ticket/).
        "ws_ticket": os.getenv("THROTTLE_RATE_WS_TICKET", "30/min"),
        # Renvoi du lien de confirmation d'e-mail : chaque appel peut
        # déclencher un e-mail réel (coût Brevo, risque de spam).
        "verification_email": os.getenv("THROTTLE_RATE_VERIFICATION_EMAIL", "5/hour"),
        # Confirmation d'un lien : freine les essais de jetons en boucle.
        "verify_email": os.getenv("THROTTLE_RATE_VERIFY_EMAIL", "30/min"),
        # Parcours de vérification : chaque appel peut solliciter l'IA.
        "parcours": os.getenv("THROTTLE_RATE_PARCOURS", "60/min"),
        # Voix de l'assistant et transcription (appels audio à l'IA).
        "voix": os.getenv("THROTTLE_RATE_VOIX", "60/min"),
    },
}
# Réglages de la documentation automatique de l'API (Swagger, /api/docs/).
SPECTACULAR_SETTINGS = {
    "TITLE": "MIMOSY API",
    "DESCRIPTION": "API de la plateforme MIMOSY de mise en relation entre clients et prestataires.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Durées volontairement courtes pour le token d'accès : un token volé ou
# intercepté ne reste exploitable qu'une demi-heure. Le refresh token dure
# une semaine, ce qui évite à un client de devoir se reconnecter trop
# souvent tout en gardant une session qui expire naturellement.
#
# La rotation des refresh tokens (ROTATE_REFRESH_TOKENS) reste désactivée :
# le frontend actuel ne stocke que le token d'accès renvoyé par
# /api/auth/token/refresh/ et ignore un éventuel nouveau refresh token.
# L'activer sans adapter le frontend déconnecterait les utilisateurs dès
# le premier rafraîchissement, puisque l'ancien refresh token serait mis
# en liste noire alors qu'il resterait le seul stocké côté client.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
# Les "middlewares" sont des filtres qui s'appliquent à chaque requête,
# dans l'ordre : CORS, sécurité, session, CSRF, authentification...
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS : liste des sites (le frontend Vue) qui ont le droit d'appeler l'API
# depuis le navigateur.
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://localhost:5174,"
    "http://127.0.0.1:5173,http://127.0.0.1:5174",
)

# L'API elle-même est authentifiée par JWT (jeton dans l'en-tête
# Authorization), pas par cookie de session : le middleware CSRF ne
# s'applique donc pas aux appels du frontend Vue vers /api/. Il reste
# actif pour /admin/, qui utilise l'authentification par session de
# Django. CSRF_TRUSTED_ORIGINS ne concerne que ce cas (accès à
# l'admin depuis un domaine différent de celui qui le sert) et reste
# vide tant qu'aucun domaine de production n'est défini.
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# Fichier qui contient la liste principale des URL.
ROOT_URLCONF = 'config.urls'

# Réglages des templates HTML (utilisés surtout par l'admin Django).
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Point d'entrée pour un serveur WSGI classique (HTTP seulement).
WSGI_APPLICATION = 'config.wsgi.application'

# ------------------------------------------------------------------
# Temps réel (Django Channels)
# ------------------------------------------------------------------
# REST reste le moyen d'effectuer les actions et la source de vérité ; les
# WebSockets servent uniquement à prévenir le navigateur qu'un événement a
# eu lieu. Voir docs/temps-reel.md.
#
# Point d'entrée ASGI : HTTP (Django, comme avant) + WebSocket (Channels).
# WSGI_APPLICATION ci-dessus est conservé pour un déploiement HTTP seul.
ASGI_APPLICATION = 'config.asgi.application'

# Channel layer : la « boîte aux lettres » qui permet à n'importe quel
# process (vue REST, thread d'analyse OCR...) d'envoyer un événement aux
# connexions WebSocket, même si elles sont ouvertes dans un autre process.
#   - REDIS_URL défini   → Redis : obligatoire dès qu'il y a plusieurs
#                           process (cas normal en production).
#   - REDIS_URL absent   → mémoire du process : suffisant en développement
#                           (un seul process), inutilisable en production.
REDIS_URL = os.getenv("REDIS_URL", "").strip()

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                # socket_timeout=None : depuis redis-py 8.0, les lectures
                # expirent par défaut après 5 s, exactement la durée du
                # BZPOPMIN bloquant de channels_redis. Sans ce réglage, le
                # consumer lève « Timeout reading from redis » toutes les
                # 5 s et chaque WebSocket est coupé puis reconnecté.
                "hosts": [{"address": REDIS_URL, "socket_timeout": None}],
                # Un événement non lu en 60 s est abandonné : un WebSocket
                # n'est pas une file d'attente, REST reste la référence.
                "expiry": 60,
            },
        },
    }
    # Cache Django partagé par tous les process, dans le même Redis :
    #   - tickets WebSocket (apps/realtime/tickets.py) : un ticket créé par un
    #     process doit être reconnu par celui qui reçoit la connexion ;
    #   - compteurs de limitation de débit (DRF throttling) : la limite
    #     s'applique alors à l'ensemble du serveur, pas process par process.
    # Des données courtes et jetables uniquement : PostgreSQL reste la source
    # de vérité, rien de métier n'est stocké dans Redis.
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "mimosy",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }
    if not DEBUG:
        import warnings

        warnings.warn(
            "REDIS_URL n'est pas défini alors que DEBUG=False : le channel layer "
            "en mémoire ne relie pas plusieurs process, les événements temps réel "
            "ne fonctionneront pas en production.",
            stacklevel=1,
        )


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Connexion à la base de données PostgreSQL. Les informations
# (nom, utilisateur, mot de passe) viennent des variables d'environnement.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # DB_* en priorité (poste de développement) ; à défaut, les noms
        # standard de l'image PostgreSQL (POSTGRES_*), pour que Docker
        # configure la base et Django avec un seul fichier, sans dupliquer
        # le mot de passe (voir docker-compose.yml).
        "NAME": os.getenv("DB_NAME") or os.getenv("POSTGRES_DB"),
        "USER": os.getenv("DB_USER") or os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD") or os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# Règles de sécurité appliquées aux mots de passe (longueur minimale,
# pas trop simple, pas uniquement des chiffres, etc.).
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Langue et fuseau horaire. USE_TZ=True : les dates sont stockées en UTC.
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Adresse web des fichiers statiques (CSS/JS de l'admin, Swagger).
STATIC_URL = 'static/'
# Dossier où « collectstatic » rassemble les fichiers statiques (admin,
# documentation de l'API) pour qu'un serveur web (nginx) les serve en
# production. Sans effet en développement (DEBUG=True).
STATIC_ROOT = Path(os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles"))

# Fichiers envoyés par les utilisateurs (photos, documents...) :
# MEDIA_URL = adresse web, MEDIA_ROOT = dossier sur le disque.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Plafond global de la taille d'un corps de requête, cohérent avec la
# limite de 5 Mo déjà imposée aux photos de profil (voir
# apps.accounts.serializers.PHOTO_TAILLE_MAX_OCTETS). Sans ce réglage,
# la valeur par défaut de Django (2,5 Mo) serait plus stricte que ce
# que l'application autorise réellement.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Les e-mails (confirmation d'adresse, voir apps.accounts.verification)
# sont envoyés par Brevo, via son API HTTP (apps.accounts.email_backends).
#   - BREVO_API_KEY défini  → envoi réel par Brevo ;
#   - BREVO_API_KEY absent  → backend console : l'e-mail s'affiche dans le
#                             terminal du serveur (développement).
# EMAIL_BACKEND reste surchargeable explicitement par l'environnement.
# Pendant les tests, Django remplace toujours ce réglage par le backend
# « locmem » : aucun e-mail réel n'est jamais envoyé par la suite de tests.

# Clé API Brevo. SECRET : uniquement dans .env, jamais dans le code, jamais
# dans les logs (le backend ne la journalise pas et ne la renvoie jamais).
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")
# Expéditeur affiché. L'adresse doit être un expéditeur validé dans Brevo.
BREVO_SENDER_EMAIL = os.getenv("BREVO_SENDER_EMAIL", "no-reply@mimosy.local")
BREVO_SENDER_NAME = os.getenv("BREVO_SENDER_NAME", "MIMOSY")
# Secondes maximum d'attente de l'API Brevo.
BREVO_TIMEOUT = float(os.getenv("BREVO_TIMEOUT", "10"))

DEFAULT_FROM_EMAIL = f"{BREVO_SENDER_NAME} <{BREVO_SENDER_EMAIL}>"

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "apps.accounts.email_backends.BrevoEmailBackend"
    if BREVO_API_KEY
    else "django.core.mail.backends.console.EmailBackend",
)

# Durée de validité d'un lien de confirmation d'adresse e-mail (heures).
EMAIL_VERIFICATION_DUREE_HEURES = int(os.getenv("EMAIL_VERIFICATION_DUREE_HEURES", "24"))
# Délai minimum (secondes) entre deux envois de lien pour un même compte,
# en plus du throttle DRF « verification_email » (par IP / utilisateur).
EMAIL_VERIFICATION_DELAI_RENVOI_SECONDES = int(os.getenv("EMAIL_VERIFICATION_DELAI_RENVOI_SECONDES", "60"))

# On utilise notre propre modèle d'utilisateur (apps/accounts/models.py)
# au lieu de celui fourni par Django.
AUTH_USER_MODEL = "accounts.User"

# Toujours actifs : ils ne dépendent pas d'un certificat HTTPS et ne
# cassent donc rien en développement local.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# Ces réglages supposent que le site est réellement servi en HTTPS,
# via un reverse proxy ou un certificat TLS placé devant Django. Les
# activer sans HTTPS réel rendrait le site inaccessible : ils ne
# s'appliquent donc qu'en dehors du développement local (DEBUG=False),
# c'est-à-dire une fois qu'un vrai déploiement HTTPS existe.
if not DEBUG:
    # Derrière un reverse proxy (nginx), c'est lui qui reçoit la connexion
    # HTTPS : il transmet le protocole d'origine dans X-Forwarded-Proto (et
    # écrase toute valeur envoyée par le client). Sans ce réglage, Django
    # croirait toujours recevoir du HTTP et redirigerait à l'infini.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HTTPS obligatoire par défaut. HTTPS_ACTIF=false sert uniquement à
    # tester la configuration de production en local, sans certificat.
    HTTPS_ACTIF = env_bool("HTTPS_ACTIF", True)
    SECURE_SSL_REDIRECT = HTTPS_ACTIF
    SESSION_COOKIE_SECURE = HTTPS_ACTIF
    CSRF_COOKIE_SECURE = HTTPS_ACTIF
    if HTTPS_ACTIF:
        SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # une semaine, à augmenter progressivement
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

# Active ou non l'analyse IA (sentiment + modération) des avis à leur
# création (voir apps.reviews.services et apps.reviews.views). Désactivée
# par défaut : les modèles utilisés (transformers/torch) sont lourds et
# nécessitent un téléchargement depuis Hugging Face au premier appel, ce
# qui ne doit pas être une condition pour que le reste du backend
# fonctionne (développement local, tests automatisés, environnement sans
# accès internet). À activer explicitement via la variable d'environnement
# une fois l'infrastructure prête à héberger ces modèles.
AVIS_ANALYSE_IA_ACTIVE = os.getenv("AVIS_ANALYSE_IA_ACTIVE", "false").lower() == "true"

# Confiance minimale (0 à 1) en dessous de laquelle une prédiction du
# modèle de sentiment/modération est ignorée plutôt qu'utilisée : une
# seule valeur centralisée (voir apps.reviews.services), pas un nombre
# répété à plusieurs endroits.
AVIS_SEUIL_CONFIANCE = float(os.getenv("AVIS_SEUIL_CONFIANCE", "0.70"))

# Même logique que AVIS_ANALYSE_IA_ACTIVE ci-dessus, appliquée à l'OCR des
# documents d'identité (voir apps.verification.services) : désactivée par
# défaut, à activer explicitement une fois l'infrastructure prête.
VERIFICATION_IA_ACTIVE = os.getenv("VERIFICATION_IA_ACTIVE", "false").lower() == "true"

# Parcours de vérification du prestataire (voir apps.verification.parcours) :
# assistant de profil, analyse du justificatif professionnel, cohérence,
# questions/relances et rapport de l'entretien. Désactivé par défaut, comme
# les autres IA : sans lui (ou sans ANTHROPIC_API_KEY), des règles
# déterministes prennent le relais et le parcours reste utilisable.
# L'IA n'est jamais l'autorité finale : la décision appartient à l'admin.
PARCOURS_IA_ACTIVE = env_bool("PARCOURS_IA_ACTIVE", False)
VERIFICATION_IA_MODELE = os.getenv("VERIFICATION_IA_MODELE", "claude-opus-5-5")

# Fournisseur d'IA générative (voir apps.common.ia_fournisseurs) :
# « gemini », « anthropic » ou « auto » (Gemini si sa clé existe, sinon Claude).
IA_FOURNISSEUR = os.getenv("IA_FOURNISSEUR", "auto")
# Clé de l'API Gemini (Google AI Studio). SECRET : uniquement dans .env.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
# Listes de modèles essayés dans l'ordre (un modèle peut être retiré ou saturé) :
# rapides pour la conversation, plus précis pour l'analyse des documents et synthèses.
GEMINI_MODELES_RAPIDES = env_list("GEMINI_MODELES_RAPIDES", "gemini-flash-lite-latest,gemini-3-flash-preview")
GEMINI_MODELES_ANALYSE = env_list("GEMINI_MODELES_ANALYSE", "gemini-3-flash-preview,gemini-flash-lite-latest")
# Synthèse vocale des assistantes IA (voir apps.common.agents_ia). Modèles
# essayés dans l'ordre : chacun a son propre quota, un modèle épuisé est
# mis en pause et le suivant prend le relais (même voix, même consignes).
GEMINI_MODELES_VOIX = env_list(
    "GEMINI_MODELES_VOIX",
    "gemini-3.1-flash-tts-preview,gemini-3.8-flash-tts,gemini-2.5-pro-preview-tts,gemini-2.5-flash-preview-tts",
)
# Modèles de voix propres à une langue (sinon GEMINI_MODELES_VOIX). Wolof :
# gemini-3.8-flash-tts est exclu par défaut, son audio en wolof étant rejeté à
# chaque phrase par le contrôle de durée (~30 s pour 12 mots, journal du
# 2026-10-06) ; tant qu'il restait dans la liste, il consommait un essai et
# écartait le modèle 5 minutes sans jamais produire de voix.
# Variable absente OU vide : la liste générale sans ce modèle.
GEMINI_MODELES_VOIX_PAR_LANGUE = {
    "wo": env_list("GEMINI_MODELES_VOIX_WO") or [m for m in GEMINI_MODELES_VOIX if m != "gemini-3.8-flash-tts"],
}
# Voix féminines retenues après essais (intelligibilité mesurée, débit posé) :
# Aby (profil) chaleureuse, Fassa (entretien) douce et précise.
GEMINI_VOIX_ABY = os.getenv("GEMINI_VOIX_ABY", "Sulafat")
GEMINI_VOIX_FASSA = os.getenv("GEMINI_VOIX_FASSA", "Vindemiatrix")
# Durée de conservation d'une phrase déjà synthétisée (économise le quota :
# l'accueil et les questions fixes ne sont générés qu'une fois).
VOIX_CACHE_SECONDES = int(os.getenv("VOIX_CACHE_SECONDES", str(30 * 24 * 3600)))
# Disjoncteur : durée pendant laquelle un modèle IA en échec (hors quota) est
# écarté au profit du suivant (apps.common.ia_fournisseurs._essayer_modeles).
IA_PAUSE_APRES_ECHEC_SECONDES = int(os.getenv("IA_PAUSE_APRES_ECHEC_SECONDES", "300"))
# Synthèse vocale lancée en arrière-plan dès qu'une phrase d'Aby ou de Fassa
# est produite (désactivée pendant les tests).
VOIX_PRECHAUFFAGE = os.getenv("VOIX_PRECHAUFFAGE", "true").lower() in ("1", "true", "yes", "on")
# Transcription des réponses orales : modèle dédié, puis modèles rapides.
GEMINI_MODELES_TRANSCRIPTION = env_list("GEMINI_MODELES_TRANSCRIPTION", "gemini-3.5-transcribe")
# Secondes maximum d'attente d'une réponse de l'IA pendant le parcours.
VERIFICATION_IA_TIMEOUT = float(os.getenv("VERIFICATION_IA_TIMEOUT", "20"))

# Langues de communication d'Aby et de Fassa (apps.common.langues) : fr, en,
# wo. Les données du profil restent toujours en français.
PARCOURS_LANGUES = env_list("PARCOURS_LANGUES", "fr,en,wo")
# Voix serveur en wolof : vide (par défaut) = pas de voix, le texte s'affiche ;
# « gemini » = essai expérimental (Gemini TTS ne documente pas le wolof : à
# faire valider par un locuteur natif avant la production).
VOIX_WOLOF = os.getenv("VOIX_WOLOF", "").strip().lower()
# Transcription du wolof par Kiriku (AIHubSN/Kiriku-Wolof-ASR, Whisper affiné
# sur le wolof), servi à part (profil Docker « asr-wolof ») : URL du service.
# Vide : transcription par le modèle Gemini généraliste avec consigne wolof.
ASR_WOLOF_URL = os.getenv("ASR_WOLOF_URL", "").strip().rstrip("/")
ASR_WOLOF_TIMEOUT = float(os.getenv("ASR_WOLOF_TIMEOUT", "60"))

# Entretien professionnel avec Fassa : 5 à 7 questions principales adaptées
# au dossier, 5 minutes maximum.
ENTRETIEN_QUESTIONS_MIN = 5
ENTRETIEN_QUESTIONS_MAX = 7
ENTRETIEN_DUREE_MAX_SECONDES = int(os.getenv("ENTRETIEN_DUREE_MAX_SECONDES", "300"))
# Taille maximale de l'enregistrement vidéo envoyé à la fin de l'entretien.
ENTRETIEN_ENREGISTREMENT_TAILLE_MAX = int(os.getenv("ENTRETIEN_ENREGISTREMENT_TAILLE_MAX", str(60 * 1024 * 1024)))

# Fallback IA de la recherche intelligente (voir apps.services.suggestions_ia) :
# appelé seulement quand la recherche classique ne trouve rien, pour proposer
# des services/catégories RÉELS du catalogue. Désactivé par défaut, comme les
# autres analyses IA : sans lui, la recherche fonctionne normalement.
RECHERCHE_IA_ACTIVE = os.getenv("RECHERCHE_IA_ACTIVE", "false").lower() == "true"
# Clé de l'API Claude (Anthropic). SECRET : uniquement dans .env, jamais dans le code.
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
RECHERCHE_IA_MODELE = os.getenv("RECHERCHE_IA_MODELE", "claude-opus-5")
# Secondes maximum d'attente de l'IA avant de répondre sans suggestion.
RECHERCHE_IA_TIMEOUT = float(os.getenv("RECHERCHE_IA_TIMEOUT", "15"))
# Durée de conservation des suggestions pour une même requête (secondes).
RECHERCHE_IA_CACHE_SECONDES = int(os.getenv("RECHERCHE_IA_CACHE_SECONDES", "3600"))

# Recherche sémantique locale : embeddings, pas IA générative. Désactivée par
# défaut afin de ne pas télécharger le modèle dans un environnement qui ne
# souhaite pas l'utiliser. Après téléchargement, LOCAL_SEULEMENT=true permet
# un fonctionnement hors ligne.
RECHERCHE_SEMANTIQUE_ACTIVE = os.getenv("RECHERCHE_SEMANTIQUE_ACTIVE", "false").lower() == "true"
RECHERCHE_SEMANTIQUE_MODELE = os.getenv(
    "RECHERCHE_SEMANTIQUE_MODELE", "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
RECHERCHE_SEMANTIQUE_LOCAL_SEULEMENT = os.getenv("RECHERCHE_SEMANTIQUE_LOCAL_SEULEMENT", "false").lower() == "true"
# Score = cosinus à 80 % + règles à 20 % maximum. En dessous de ce seuil,
# aucun résultat n'est affiché comme pertinent.
RECHERCHE_SEMANTIQUE_SEUIL = float(os.getenv("RECHERCHE_SEMANTIQUE_SEUIL", "0.58"))
RECHERCHE_SEMANTIQUE_CACHE_SECONDES = int(os.getenv("RECHERCHE_SEMANTIQUE_CACHE_SECONDES", "86400"))

# Seuil minimal de ressemblance (SequenceMatcher.ratio) en dessous duquel
# un champ extrait de la CNI est considéré comme ne correspondant pas aux
# données d'inscription (voir apps.verification.services.comparer_avec_profil).
# Valeur par défaut 0.80 : une correspondance quasi-exacte est requise, mais
# la normalisation (casse + accents + espaces) est appliquée avant la comparaison.
# En production, augmenter vers 0.85–0.90 pour réduire les faux positifs ;
# diminuer vers 0.70 si des erreurs OCR fréquentes rejettent des documents légitimes.
_seuil_brut = os.getenv("SEUIL_CORRESPONDANCE_CHAMP", "0.80")
try:
    SEUIL_CORRESPONDANCE_CHAMP = float(_seuil_brut)
    if not (0.0 < SEUIL_CORRESPONDANCE_CHAMP <= 1.0):
        raise ValueError(f"Valeur hors intervalle (0, 1] : {SEUIL_CORRESPONDANCE_CHAMP}")
except (ValueError, TypeError) as _e:
    import warnings
    warnings.warn(
        f"SEUIL_CORRESPONDANCE_CHAMP invalide ({_seuil_brut!r}) : {_e}. "
        "La valeur par défaut 0.80 est utilisée.",
        stacklevel=1,
    )
    SEUIL_CORRESPONDANCE_CHAMP = 0.80

# Fournisseur de paiement réellement appelé (voir apps.wallet.providers).
# "sandbox" par défaut : aucun paiement réel tant que PayDunya n'est pas
# explicitement configuré avec de vraies clés API ("paydunya"). MIMOSY
# n'intègre plus Wave/Orange Money directement : PayDunya est
# l'unique fournisseur externe, et route lui-même les déboursements
# vers Wave Sénégal / Orange Money Sénégal (voir apps.wallet.providers.paydunya).
PAYMENT_PROVIDER = os.getenv("PAYMENT_PROVIDER", "sandbox")

# Délai (minutes) après lequel un paiement resté INITIE est considéré
# comme abandonné : MIMOSY a créé le paiement mais n'a jamais reçu la
# réponse de PayDunya (serveur arrêté pendant l'appel, par exemple).
# Passé ce délai, il devient ECHOUE et le client peut réessayer.
PAYMENT_INITIE_TIMEOUT_MINUTES = int(os.getenv("PAYMENT_INITIE_TIMEOUT_MINUTES", "10"))

# Taux de commission MIMOSY, centralisé ici plutôt que codé en dur dans
# chaque endroit qui en a besoin (voir apps.wallet.services).
COMMISSION_TAUX = Decimal(os.getenv("COMMISSION_TAUX", "0.10"))

# Délai laissé à un prestataire pour refaire une prestation contestée
# après une décision administrative "reprise" sur un litige (voir
# apps.disputes.views.LitigeViewSet.demander_reprise).
LITIGE_DELAI_REPRISE_HEURES = int(os.getenv("LITIGE_DELAI_REPRISE_HEURES", "24"))

# Répartition financière appliquée quand un litige est réattribué à un
# nouveau prestataire après expiration du délai de reprise (voir
# apps.disputes.views.LitigeViewSet.reattribuer) : la part du prestataire
# initial se déduit de celle-ci (1 - LITIGE_REATTRIBUTION_PART_NOUVEAU).
LITIGE_REATTRIBUTION_PART_NOUVEAU = Decimal(os.getenv("LITIGE_REATTRIBUTION_PART_NOUVEAU", "0.75"))

# Délai laissé au client pour valider une prestation que le prestataire a
# marquée comme réalisée (statut REALISEE). Passé ce délai, sans litige
# ouvert, la prestation est validée automatiquement et les fonds sont
# libérés (voir apps.prestations.services.valider_prestations_expirees).
PRESTATION_DELAI_VALIDATION_HEURES = int(os.getenv("PRESTATION_DELAI_VALIDATION_HEURES", "72"))

# Credentials PayDunya (voir apps.wallet.paydunya_client.PayDunyaClient).
# Lus dans l'environnement (back_Mimosy/.env.docker avec Docker, .env
# sinon ; ces deux fichiers sont ignorés par Git) : une clé écrite dans
# le code resterait dans l'historique Git pour toujours et serait
# partagée avec quiconque clone le dépôt.
# Jamais de valeur par défaut réelle ici : en l'absence de ces trois
# clés, PayDunyaClient refuse explicitement de s'instancier plutôt que
# d'échouer silencieusement ou d'appeler l'API avec des clés vides.
PAYDUNYA_MASTER_KEY = os.getenv("PAYDUNYA_MASTER_KEY", "")
PAYDUNYA_PRIVATE_KEY = os.getenv("PAYDUNYA_PRIVATE_KEY", "")
PAYDUNYA_TOKEN = os.getenv("PAYDUNYA_TOKEN", "")

# "test" par défaut, jamais "live" : le passage en mode réel doit être
# une décision explicite de déploiement, jamais un défaut implicite.
# Décidé uniquement côté serveur (voir apps.wallet.paydunya_client) :
# le frontend ne peut jamais transmettre ni influencer ce choix.
PAYDUNYA_MODE = os.getenv("PAYDUNYA_MODE", "test")

# Démonstration du retrait SANS déboursement PayDunya. L'API de déboursement
# PayDunya (api/v2/disburse) n'accepte que des clés LIVE : avec des clés de
# test, elle répond "LIVE Private Key and Token combination is invalid",
# il n'existe pas de payout de test. Activé, ce mode fait passer le retrait
# par tout le parcours interne (validation, déduction verrouillée,
# transaction, idempotence) puis le marque SIMULE — jamais REUSSI, et sans
# appeler PayDunya. N'a AUCUN effet si PAYDUNYA_MODE=live : un retrait réel
# ne peut jamais être remplacé par une simulation (voir
# apps.wallet.providers.paydunya.payout_demo_actif).
PAYDUNYA_PAYOUT_DEMO = os.getenv("PAYDUNYA_PAYOUT_DEMO", "false").lower() == "true"

# URLs que PayDunya appelle depuis ses propres serveurs (jamais depuis
# le navigateur du client) pour confirmer, de façon asynchrone, l'issue
# d'un paiement ou d'un déboursement. Doivent être des URLs absolues et
# joignables publiquement (donc vides et sans effet en développement
# local tant qu'aucun tunnel/déploiement ne les rend accessibles).
PAYDUNYA_CALLBACK_URL = os.getenv("PAYDUNYA_CALLBACK_URL", "")
PAYDUNYA_PAYOUT_CALLBACK_URL = os.getenv("PAYDUNYA_PAYOUT_CALLBACK_URL", "")

# Base du frontend Vue, utilisée pour construire les URLs de retour
# (return_url/cancel_url) transmises à PayDunya lors de la création
# d'une facture de paiement : après avoir payé, PayDunya redirige le
# client vers cette adresse, jamais vers une URL fournie par la requête.
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")

# Journalisation du wallet (paiements PayDunya) : sans cette entrée, seuls
# les avertissements (WARNING) seraient visibles, car aucune configuration
# LOGGING n'existait. Portée volontairement limitée au logger "apps.wallet" :
# les autres journaux (Django, autres apps) gardent leur comportement.
# Le code du wallet ne journalise jamais de clé PayDunya, de hash, ni de
# valeur de token de facture (voir apps/wallet/services.py).
# Configuration des journaux (logs) affichés dans le terminal.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "{levelname} {asctime} {name} : {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "loggers": {
        "apps.wallet": {"handlers": ["console"], "level": "INFO", "propagate": False},
        # Envoi des e-mails (Brevo) : jamais de clé API, de jeton ni de lien
        # de confirmation dans ces journaux (voir apps.accounts.verification).
        "apps.accounts": {"handlers": ["console"], "level": "INFO", "propagate": False},
        # Fournisseurs d'IA : modèle utilisé pour chaque voix, quotas épuisés (jamais de clé).
        "apps.common": {"handlers": ["console"], "level": "INFO", "propagate": False},
        # Voix d'Aby et de Fassa : une ligne par phrase servie ou refusée (agent,
        # index, langue, code d'erreur, durée, taille) ; jamais le texte lui-même.
        "apps.verification": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}


# Tests automatisés : jamais d'appel à une IA réelle (coût, données de test
# envoyées à un tiers, résultats non reproductibles), même si .env contient
# des clés. Les tests qui vérifient l'IA la simulent explicitement.
import sys as _sys

if len(_sys.argv) > 1 and _sys.argv[1] == "test":
    GEMINI_API_KEY = ""
    ANTHROPIC_API_KEY = ""
    IA_FOURNISSEUR = "auto"
    PARCOURS_IA_ACTIVE = False
    PARCOURS_LANGUES = ["fr", "en", "wo"]
    VOIX_WOLOF = ""
    ASR_WOLOF_URL = ""
    VOIX_PRECHAUFFAGE = False
    # Les fichiers envoyés pendant les tests (pièces d'identité, vidéos...)
    # vont dans un dossier temporaire, supprimé à la fin : media/ n'est plus pollué.
    import atexit as _atexit
    import shutil as _shutil
    import tempfile as _tempfile

    MEDIA_ROOT = Path(_tempfile.mkdtemp(prefix="mimosy-tests-media-"))
    _atexit.register(_shutil.rmtree, MEDIA_ROOT, ignore_errors=True)
