# Generated by Django 6.1.1 on 2026-09-21 10:40

import apps.disputes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestations', '0003_demandeprestation_service'),
        ('profiles', '0002_profilprestataire_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('description_client', models.TextField(blank=True)),
                ('description_prestataire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', "En cours d'examen"), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('decision_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges_client', to=settings.AUTH_USER_MODEL)),
                ('demande_prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litiges', to='prestations.demandeprestation')),
                ('ouvert_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges_ouverts', to=settings.AUTH_USER_MODEL)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litiges_recus', to='profiles.profilprestataire')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PreuveLitige',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_preuve', models.CharField(choices=[('PHOTO_AVANT', 'Photo avant'), ('PHOTO_APRES', 'Photo après'), ('DOCUMENT', 'Document'), ('DEVIS', 'Devis'), ('FACTURE', 'Facture'), ('AUTRE', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to=apps.disputes.models.chemin_preuve)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('deposee_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves_deposees', to=settings.AUTH_USER_MODEL)),
                ('litige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='disputes.litige')),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
    ]
