# Generated by Django 6.1.1 on 2026-09-21 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('profiles', '0002_profilprestataire_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='litige',
            name='date_confirmation_reprise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='date_decision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='date_limite_reprise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litige',
            name='fonds_geles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='litige',
            name='montant_concerne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='litige',
            name='nouveau_prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='litiges_recus_par_reattribution', to='profiles.profilprestataire'),
        ),
        migrations.AlterField(
            model_name='litige',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', "En cours d'examen"), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté'), ('REPRISE_DEMANDEE', 'Reprise demandée'), ('REPRISE_EFFECTUEE', 'Reprise effectuée'), ('DELAI_EXPIRE', 'Délai de reprise expiré'), ('REATTRIBUE', 'Réattribué à un autre prestataire')], default='EN_ATTENTE', max_length=20),
        ),
    ]
