# Generated by Django 6.1.1 on 2026-09-20 16:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestations', '0003_demandeprestation_service'),
        ('profiles', '0002_profilprestataire_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='INITIE', max_length=20)),
                ('provider', models.CharField(choices=[('SANDBOX', 'Sandbox (test, jamais un vrai paiement)'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=20)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('fonds_liberes', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('demande_prestation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='prestations.demandeprestation')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solde_bloque', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('prestataire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='profiles.profilprestataire')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BLOCAGE', 'Fonds bloqués (paiement client)'), ('COMMISSION', 'Commission MIMOSY'), ('LIBERATION', 'Fonds libérés (disponibles)'), ('RETRAIT', 'Retrait'), ('REMBOURSEMENT', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.UUIDField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('provider', models.CharField(choices=[('SANDBOX', 'Sandbox (test, jamais un vrai paiement)'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=20)),
                ('destination', models.CharField(help_text='Numéro mobile money de destination', max_length=30)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='profiles.profilprestataire')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='wallet.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('solde_bloque__gte', 0)), name='wallet_solde_bloque_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('solde_disponible__gte', 0)), name='wallet_solde_disponible_non_negatif'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'date_creation'], name='wallet_tran_wallet__be2837_idx'),
        ),
    ]
