# Generated by Django 6.1.1 on 2026-09-20 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0003_demandeprestation_service'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='demande_prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='prestations.demandeprestation'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'REUSSI')), fields=('demande_prestation',), name='un_seul_paiement_reussi_par_demande'),
        ),
    ]
