# Generated by Django 6.1.1 on 2026-09-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_payment_demande_prestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox (test, jamais un vrai paiement)'), ('PAYDUNYA', 'PayDunya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='provider',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox (test)'), ('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=20),
        ),
    ]
