# Generated by Django 6.1.1 on 2026-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilprestataire_date_naissance'),
        ('wallet', '0003_alter_payment_provider_alter_withdrawal_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='solde_gele',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BLOCAGE', 'Fonds bloqués (paiement client)'), ('COMMISSION', 'Commission MIMOSY'), ('LIBERATION', 'Fonds libérés (disponibles)'), ('RETRAIT', 'Retrait'), ('REMBOURSEMENT', 'Remboursement'), ('GEL_LITIGE', 'Fonds gelés (litige)'), ('DEGEL_LITIGE', 'Fonds dégelés (litige résolu)'), ('REATTRIBUTION_LITIGE', 'Réattribution (litige)')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('solde_gele__gte', 0)), name='wallet_solde_gele_non_negatif'),
        ),
    ]
