# Generated by Django 6.1.1 on 2026-09-26 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0003_demandeprestation_service'),
        ('wallet', '0004_wallet_solde_gele_alter_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url_paiement',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statut',
            field=models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé'), ('A_REMBOURSER', 'À rembourser (payé en double)')], default='INITIE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['INITIE', 'EN_ATTENTE', 'REUSSI'])), fields=('demande_prestation',), name='un_seul_paiement_actif_par_demande'),
        ),
    ]
