# Generated by Django 6.1.1 on 2026-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_payment_url_paiement_alter_payment_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], default='', max_length=20),
        ),
    ]
