# Generated by Django 6.1.1 on 2026-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_payment_moyen_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('SIMULE', 'Simulation de démonstration')], default='EN_ATTENTE', max_length=20),
        ),
    ]
