# Generated by Django 6.1.1 on 2026-09-14 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_cible', models.CharField(choices=[('AVIS', 'Avis'), ('COMPORTEMENT', 'Comportement'), ('AUTRE', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TRAITE', 'Traité'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
