# Generated by Django 6.1.1 on 2026-09-14 12:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(default='PUBLIE', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_rediges', to=settings.AUTH_USER_MODEL)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to='profiles.profilprestataire')),
            ],
        ),
    ]
