# Generated by Django 6.1.1 on 2026-09-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0002_alter_demandeprestation_client_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='est_inapproprie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='prestation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='prestations.demandeprestation'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('NEUTRE', 'Neutre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='statut',
            field=models.CharField(choices=[('PUBLIE', 'Publié'), ('EN_ATTENTE', 'En attente'), ('REJETE', 'Rejeté')], default='PUBLIE', max_length=20),
        ),
    ]
