# Generated by Django 6.1.1 on 2026-09-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0002_alter_demandeprestation_client_and_more'),
        ('reviews', '0002_avis_est_inapproprie_avis_prestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='prestation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='prestations.demandeprestation'),
        ),
    ]
