# Generated by Django 6.1.1 on 2026-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_avis_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='date_analyse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='score_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='score_toxicite',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
