# Generated by Django 6.1.1 on 2026-09-14 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('DEMANDE_PRESTATION', 'Demande de prestation'), ('DEMANDE_DEVIS', 'Demande de devis'), ('REPONSE_PRESTATION', 'Réponse de prestation'), ('REPONSE_DEVIS', 'Réponse de devis'), ('MESSAGE', 'Message'), ('AVIS', 'Avis')], max_length=30)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
