# Generated by Django 6.1.1 on 2026-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEMANDE_PRESTATION', 'Demande de prestation'), ('DEMANDE_DEVIS', 'Demande de devis'), ('REPONSE_PRESTATION', 'Réponse de prestation'), ('REPONSE_DEVIS', 'Réponse de devis'), ('MESSAGE', 'Message'), ('AVIS', 'Avis'), ('RENDEZ_VOUS', 'Rendez-vous'), ('VERIFICATION', "Vérification d'identité"), ('SIGNALEMENT', 'Signalement'), ('LITIGE', 'Litige')], max_length=30),
        ),
    ]
